export const CLASS_STATES_ACTIVED = 'nv-actived'
export const CLASS_STATUS_DISABLED = 'nv-disabled'
export const CLASS_STATES_HOVER = 'nv-hover'
export const CLASS_STATES_FOCUS = 'nv-focusin'
export const CLASS_STATES_HIDE = 'nv-hide'
export const CLASS_STATES_ROLLING = 'nv-rolling'